
language: cpp
sudo: false

compiler:
  - gcc

before_install:
  - echo $LANG

script: cmake . && make

branches:
  only:
    - master

notifications:
  email: andre.zelak@gmail.com

os:
  - linux
  - osx
